
# Numpy Exercises

![alt text](https://i.morioh.com/b53d97587a.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays. 

In [1]:
# Import library
import numpy as np

For each of this exercise, try different method to produce the output

### Create numpy array

In [ ]:
# Create an 1D array / row vector 
# Expected output: [1 2 3 4 5 6]
# Print out the shape of the array

# Your code here

answer_1 = np.array([1, 2, 3, 4, 5, 6]) # More work 
print(f"Method 1: {answer_1}")

answer_2 = np.array([i for i in range(1, 7)]) # Better but not as optimized as answer_3
print(f"Method 2: {answer_2}")

answer_3 = np.arange(1, 7) 
print(f"Method 3: {answer_3}")

Method 1: [1 2 3 4 5 6]
Method 2: [1 2 3 4 5 6]
Method 3: [1 2 3 4 5 6]


In [3]:
# Create an 2D array / matrix
# Expected output: [[1 2 3]
#                   [4 5 6]]

# Your code here
method_1 = np.array(
    [
     [1, 2, 3],
     [4, 5, 6]
    ]
)
print(method_1)

# Another way, combining np.arange and reshape
method_2 = np.arange(1,7).reshape(2,3)
print(method_2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Create an array of all zeros with the shape (1, 4)
# Expected output: [[0. 0. 0. 0.]]

# Your code here

answer = np.zeros(shape = (1, 4), dtype = "float32")
answer

array([[0., 0., 0., 0.]], dtype=float32)

In [ ]:
# Create an array of all ones with the shape (2, 5)
# Expected output: [[1. 1. 1. 1. 1.]
#                   [1. 1. 1. 1. 1.]]

# Your code here

answer = np.ones(shape = (2, 5), dtype = "float32")
answer

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Create a constant array
# Expected output: [[7 7]
#                   [7 7]]

# Your code here

answer = np.ones(shape = (2, 2), dtype = "int32") * 7
answer

array([[7, 7],
       [7, 7]], dtype=int32)

In [ ]:
# Create a range of integer numbers as a numpy array 
# Expected output: [5 6 7]

# Your code here

answer = np.arange(5, 8)
answer

array([5, 6, 7])

In [ ]:
# Create an array of evenly spaced numbers in an interval
# Expected output: [ 2.  4.  6.  8. 10.]

# Your code here

answer_1 = np.arange(2, 12, 2, dtype = "float32")
print(f"Method 1: {answer_1}")

answer_2 = np.linspace(2, 10, 5, dtype = "float32")
print(f"Method 2: {answer_2}")

Method 1: [ 2.  4.  6.  8. 10.]
Method 2: [ 2.  4.  6.  8. 10.]


In [ ]:
# Create an array of random number
# Expected output: An 3x3x3 array of random numbers

# Your code here

# Drawn from normal distribution
answer_1 = np.random.randn(3, 3, 3)
print(f"Method 1: {answer_1}")

print("\n")

# Drawn from uniform distribution
answer_2 = np.random.rand(3, 3, 3)
print(f"Method 2: {answer_2}")

Method 1: [[[ 1.12935648 -0.40421472 -0.99009484]
  [ 1.06511568  1.19477262 -0.61360381]
  [ 0.22123226  0.04320455 -0.14613107]]

 [[-1.32269768  0.04863155  2.35966611]
  [ 0.65144715 -0.87815676 -0.66131915]
  [ 3.43580811  0.64925745 -0.27944883]]

 [[ 1.23632354 -1.58039697  0.92391707]
  [ 0.14135451 -1.12372959  1.09604784]
  [-0.2946265  -0.25565014  0.4586468 ]]]


Method 2: [[[0.41632555 0.40867898 0.24842183]
  [0.75156016 0.71279559 0.01150545]
  [0.26121507 0.78957191 0.52207452]]

 [[0.54681665 0.68178333 0.40413399]
  [0.06667037 0.88842158 0.18057825]
  [0.29790541 0.34489158 0.15221237]]

 [[0.49621582 0.47287728 0.28158711]
  [0.69778199 0.772975   0.58991546]
  [0.468096   0.81145004 0.62501187]]]


In [ ]:
# Create a 2d array with 1 on the border and 0 inside
# Expected output: [[1., 1., 1., 1., 1., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 1., 1., 1., 1., 1.]])
# Your code here

answer = np.ones(shape = (6, 6), dtype = "float32")
answer[1:-1, 1:-1] = 0 # slicing
answer

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [5]:
# Create 5 random integers between 2 and 40
# (Take a look at np random library: https://numpy.org/doc/1.16/reference/routines.random.html)

# Your code here

answer = np.random.randint(2, 40, 5)
answer

array([22, 34, 33,  5, 36])

In [6]:
# Create a 4x6 matrix containing random numbers between -2 and 2
# Your code here

answer = np.random.uniform(low = -2, high = 2, size = (4, 6))
answer

array([[ 1.9324027 ,  1.46924464, -1.06548087,  0.90271954,  0.49156579,
        -1.4265901 ],
       [-0.76414465, -1.98702494,  0.53710527, -0.79383415,  1.70874805,
        -1.40075018],
       [ 1.36804253, -0.22516184,  0.22147397,  0.8534881 , -1.893608  ,
         1.59414814],
       [ 0.2256293 , -1.99873088,  0.74811984,  1.26447482,  0.70058024,
         1.74067159]])

### Describing a matrix

In [ ]:
a = np.array([ np.ones(5), np.ones(5) ])  # (2, 5)
b = np.array([ np.zeros(5), np.zeros(5) ])
c = np.array([ np.zeros(5), np.zeros(5) ])

r = np.array([a, b, c])

**Try to answer the question by yourself first, and double-check by code**

In [ ]:
# What is the shape of r?

answer = r.shape
answer

(3, 2, 5)

In [ ]:
# How many number of elements in r

answer = r.size
answer

30

In [ ]:
# How many dimensions do r have?

answer = r.ndim
answer

3

### Indexing

In [7]:
e = np.array([[1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9,  10,  11,  12]])

In [ ]:
# Get the number 7 in array e using indexing
# Expected result: 7

# Your code here

answer = e[1, 2]
answer

7

In [ ]:
# Get the the first row of array e
# Expecte result: [1 2 3 4]

# Your code here

answer = e[0]
answer

array([1, 2, 3, 4])

In [ ]:
# Get the the first column of array e
# Expected result: [1 5 9]

# Your code here

answer = e[:, 0]
answer

array([1, 5, 9])

In [9]:
# Get the second and last columns
# Expected result: [[ 2  4]
#                   [ 6  8]
#                   [10 12]]

# Your code here

answer = e[:, [1,3]]
answer

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [10]:
# Get the reversed array of e (elements go backward)
# Expected result: [[12 11 10  9]
#                   [ 8  7  6  5]
#                   [ 4  3  2  1]]

# Your code here

answer = e[::-1, ::-1]
answer

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

## Boolean indexing

In [17]:
a = np.concatenate([np.arange(1,8),np.arange(6,0,-1)],axis=0)
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [12]:
# Get all the numbers that are more than 5
# Your code here

answer = a[a > 5]
answer

array([6, 7, 6])

In [13]:
# Get all the numbers that are more than 3 but less than 5
# Your code here

answer = a[(a > 3) & (a < 5)]
answer

array([4, 4])

In [14]:
# Get the indices of those numbers that are more than 5
# Your answer should be [5 6 7]
# Your code here

answer = np.where(a > 5)
answer

(array([5, 6, 7]),)

In [18]:
# Turn all the numbers > 5 to 1, and all numbers <=5 to 0
# Your answer should be [0 0 0 0 0 1 1 1 0 0 0 0 0]
# Your code here
# (also try to do this using 1 line of code)

method_1 = (a > 5).astype("int32")
print(method_1)

method_2 = np.where(a>5,1,0)
print(method_2)

[0 0 0 0 0 1 1 1 0 0 0 0 0]
[0 0 0 0 0 1 1 1 0 0 0 0 0]


In [19]:
a = np.array([1,2,0,0,4])

In [20]:
# Find indices of non-zero elements from a
# Your code here

answer = np.where(a != 0)
answer

(array([0, 1, 4]),)

## Transposing

In [21]:
a = np.array([[1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9,  10,  11,  12]])
b = np.array([[6, 3, 7, 4],
       [6, 9, 2, 6]])

# Find a way to do matrix multiplication between a and b
# Expected result:[[ 49,  54],
                    # [129, 146],
                    # [209, 238]]


b_transpose = b.T # switching from shape (2,4) to (4,2)
answer = a @ b_transpose # (3,4) @ (4,2) => (3,2)
answer

array([[ 49,  54],
       [129, 146],
       [209, 238]])


## Reshape array

In [22]:
# Create a 3x3 matrix with the values ranging from 10 to 18
# Expected result: [[10, 11, 12],
#                   [13, 14, 15],
#                   [16, 17, 18]]
# Your code here

answer = np.arange(10, 19).reshape(3, 3)
answer

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [23]:
# Reshape 2x3 maxtrix b to an 1x6 row vector
# Expected result: [[1 2 3 4 5 6]]
b = np.array([[1,2,3],
              [4,5,6]])

# Your code here

answer_1 = b.reshape(1, 6)
print(f"Method 1: {answer_1}")

answer_2 = b.reshape(1, -1)
print(f"Method 2: {answer_2}")

Method 1: [[1 2 3 4 5 6]]
Method 2: [[1 2 3 4 5 6]]


In [24]:
# Reshape the previous 1x6 row vector to an 6x1 column vector
# Expected result: [[1]
#                   [2]
#                   [3]
#                   [4]
#                   [5]
#                   [6]]

# Your code here

answer = b.reshape(1, 6)
answer = answer.T
answer

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Aggregate functions

In [27]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s)

# Maximum number for the whole matrix
arr_max = s.max() # same as arr_max = np.max(s)
print("Max:", arr_max, sep = "\n")

# Minimum number for the whole matrix
arr_min = s.min() # same as arr_max = np.min(s)
print("Min:", arr_min, sep = "\n")

# Max element in each column
col_max = s.max(axis = 0) # same as arr_max = np.max(s,axis=0)
print("Max in each column:", col_max, sep = "\n")

# Min element in each row
row_min = s.min(axis = 1) # same as arr_max = np.min(s,axis=1)
print("Min in each row:", row_min, sep = "\n")

# Mean
arr_mean = s.mean() # same as arr_max = np.mean(s)
print("Mean:", arr_mean, sep = "\n")

# Standard Deviation 
arr_sd = s.std() # same as arr_max = np.std(s)
print("Standard Dev.:", arr_sd, sep = "\n")

#Variance
arr_v = s.var() # same as arr_max = np.var(s)
print("Variance:", arr_v, sep = "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:
9
Min:
1
Max in each column:
[7 8 9]
Min in each row:
[1 4 7]
Mean:
5.0
Standard Dev.:
2.581988897471611
Variance:
6.666666666666667


## A bit more challenge

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
# Expected result: [ 0  1  2 -3 -4 -5 -6 -7 -8  9]
a = np.arange(10)

# Your code here
a[(a >= 3) & (a <= 8)] *= -1
print(a)



array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
# Expected result: [[0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]]

# Your code here

# using broadcasting
placeholder = np.zeros(shape = (5, 5), dtype = "float32")
pad = np.arange(0, 5, dtype = "float32")
answer = placeholder + pad
answer

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]], dtype=float32)

In [ ]:
# Give a random vector of size 10, replace the maximum value by 0
Z = np.random.random(10)

# Your code here

Z[Z == Z.max()] = 0
Z

array([8.74608199e-01, 1.66120549e-01, 7.92251707e-04, 7.48813507e-01,
       6.99167603e-01, 2.47460815e-01, 0.00000000e+00, 5.17299072e-01,
       7.96396779e-02, 6.82688621e-01])

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

print(a, b)

[9 5 0 0 0 3 8 9 8 6] [9 8 2 1 8 9 3 0 6 2]


In [ ]:
# Find the common values between these 2 arrays:
# a = np.random.randint(0,10,10)
# b = np.random.randint(0,10,10)

# Your code here

answer = np.intersect1d(a, b)
answer

array([0, 3, 6, 8, 9])

In [ ]:
a = np.array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])
# Sort this array
# Expected result: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Your code here

# This method returns a new array
answer_1 = np.sort(a)
print(f"Method 1: {answer_1}")

# This method is inplace
a.sort()
print(f"Method 2: {a}")

Method 1: [0 1 2 3 4 5 6 7 8 9]
Method 2: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# For the same array above, return the indices that would sort the array
# Expected result: [3, 1, 5, 8, 7, 2, 9, 4, 0, 6]
# Your code here

a = np.array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])

answer = np.argsort(a)
answer

array([3, 1, 5, 8, 7, 2, 9, 4, 0, 6])

In [ ]:
a = np.array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8],
       [8, 3, 8]])
# Sort each column of this matrix, in descending order
# Expected result:
# [[9, 8, 9],
# [8, 8, 8],
# [6, 3, 8],
# [5, 3, 6],
# [0, 0, 4]]
#
# your code here

answer = np.sort(a, axis = 0)[::-1]
answer

array([[9, 8, 9],
       [8, 8, 8],
       [6, 3, 8],
       [5, 3, 6],
       [0, 0, 4]])

In [31]:
# Create an 1D array / row vector containing these float numbers 
# Expected output: [0.5, 0.6, 0.7]
#
# Note: try to use np.arange to solve this. Also try using np.linspace
# (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)
#
# Your code here

# be careful with using np.arange in this case, due to floating number rounding error. In this case, please use linspace
print(f'Bad way: {np.arange(0.5,0.8,0.1)}') # computer doesn't really interpret number 0.8 as it is, it will actually be something like 0.8000000000001
print(f'Good way: {np.linspace(0.5,0.7,3)}')


Bad way: [0.5 0.6 0.7 0.8]
Good way: [0.5 0.6 0.7]


In [33]:
np.random.seed(42)
a = np.random.rand(5)
b = np.array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])
print(a)
print(b)

# Write 1 line of code to check whether all elements in these 2 arrays are equal

# Similarly to above, what are printed is not exactly what are stored. 
# Using np.array_equal (to check whether all value of each array are equal) will return False
answer = np.array_equal(a, b)
print(answer)

# Better way is to use np.allclose that allow a small difference
answer = np.allclose(a,b)
print(answer)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
False
True


In [ ]:
a = np.random.randint(10,size=5)
# Find the total memory size of this array in byte
# Hint: use a.itemsize to get the size (in byte) of 1 SINGLE ELEMENT
# Your code here

answer = a.size * a.itemsize
answer

40

In [ ]:
# Convert array a above to type int8 and recalculate its memory size
# Hint: use astype to convert to another type
# Your code here

a = a.astype("int8")
answer = a.size * a.itemsize
answer

5

In [ ]:
a = np.array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8],
       [8, 3, 8]])
# Subtract each row of this matrix by the mean of each row
# Expected result: 
# [[ 2.        ,  1.        , -3.        ],
# [-0.66666667, -2.66666667,  3.33333333],
# [-0.66666667,  1.33333333, -0.66666667],
# [-2.66666667, -2.66666667,  5.33333333],
# [ 1.66666667, -3.33333333,  1.66666667]]

# Your code here

mean = np.expand_dims(a.mean(axis = 1), axis = 1)
answer = a - mean
answer

array([[ 2.        ,  1.        , -3.        ],
       [-0.66666667, -2.66666667,  3.33333333],
       [-0.66666667,  1.33333333, -0.66666667],
       [-2.66666667, -2.66666667,  5.33333333],
       [ 1.66666667, -3.33333333,  1.66666667]])

In [ ]:
a = np.arange(25).reshape(5,5)
# Swap the first row and the last row of this array
# Your code here

print(f"Original: {a}")
tmp = a[0]
a[0] = a[-1]
a[-1] = tmp
print(f"After: {a}")

Original: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After: [[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
