
# Numpy Exercises

![alt text](https://i.morioh.com/b53d97587a.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays. 

In [ ]:
# Import library
import numpy as np

For each of this exercise, try different method to produce the output

### Create numpy array

In [ ]:
# Create an 1D array / row vector 
# Expected output: [1 2 3 4 5 6]
# Print out the shape of the array

# Your code here


In [ ]:
# Create an 2D array / matrix
# Expected output: [[1 2 3]
#                   [4 5 6]]

# Your code here


In [ ]:
# Create an array of all zeros with the shape (1, 4)
# Expected output: [[0. 0. 0. 0.]]

# Your code here


In [ ]:
# Create an array of all ones with the shape (2, 5)
# Expected output: [[1. 1. 1. 1. 1.]
#                   [1. 1. 1. 1. 1.]]

# Your code here


In [ ]:
# Create a constant array
# Expected output: [[7 7]
#                   [7 7]]

# Your code here


In [ ]:
# Create a range of integer numbers (below) as numpy array
# Expected output: [5 6 7]

# Your code here


In [ ]:
# Create an array of evenly spaced numbers in an interval
# Expected output: [ 2.  4.  6.  8. 10.]

# Your code here


In [ ]:
# Create an array of random number
# Expected output: An 3x3x3 array of random numbers

# Your code here


In [ ]:
# Create a 2d array with 1 on the border and 0 inside
# Expected output: [[1., 1., 1., 1., 1., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 0., 0., 0., 0., 1.],
#                   [1., 1., 1., 1., 1., 1.]])
# Your code here


In [ ]:
# Create 5 random integers between 2 and 40
# (Take a look at np random library: https://numpy.org/doc/1.16/reference/routines.random.html)

# Your code here


In [ ]:
# Create a 4x6 matrix containing random numbers between -2 and 2
# Your code here


### Describing a matrix

In [ ]:
a = np.array([ np.ones(5), np.ones(5) ])  # (2, 5)
b = np.array([ np.zeros(5), np.zeros(5) ])
c = np.array([ np.zeros(5), np.zeros(5) ])

r = np.array([a, b, c])

**Try to answer the question by yourself first, and double-check by code**

In [ ]:
# What is the shape of r?


In [ ]:
# How many number of elements in r


In [ ]:
# How many dimensions do r have?


### Indexing

In [ ]:
e = np.array([[1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9,  10,  11,  12]])

In [ ]:
# Get the number 7 in array e using indexing
# Expected result: 7

# Your code here


In [ ]:
# Get the the first row of array e
# Expecte result: [1 2 3 4]

# Your code here


In [ ]:
# Get the the first column of array e
# Expected result: [1 5 9]

# Your code here


In [ ]:
# Get the second and last columns
# Expected result: [[ 2  4]
#                   [ 6  8]
#                   [10 12]]

# Your code here


In [ ]:
# Get the reversed array of e (elements go backward)
# Expected result: [[12 11 10  9]
#                   [ 8  7  6  5]
#                   [ 4  3  2  1]]

# Your code here


## Boolean indexing

In [ ]:
a = np.concatenate([np.arange(1,8),np.arange(6,0,-1)],axis=0)
a

In [ ]:
# Get all the numbers that are more than 5
# Your code here


In [ ]:
# Get all the numbers that are more than 3 but less than 5
# Your code here


In [ ]:
# Get the indices of those numbers that are more than 5
# Your answer should be [5 6 7]
# Your code here

In [ ]:
# Turn all the numbers > 5 to 1, and all numbers <=5 to 0
# Your answer should be [0 0 0 0 0 1 1 1 0 0 0 0 0]
# Your code here
# (also try to do this using 1 line of code)



In [ ]:
a = np.array([1,2,0,0,4])
# Find indices of non-zero elements from a
# Your code here



## Transposing

In [ ]:
a = np.array([[1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9,  10,  11,  12]])
b = np.array([[6, 3, 7, 4],
       [6, 9, 2, 6]])

# Find a way to do matrix multiplication between a and b
# Expected result:[[ 49,  54],
                    # [129, 146],
                    # [209, 238]]



## Reshape array

In [ ]:
# Create a 3x3 matrix with the values ranging from 10 to 18
# Expected result: [[10, 11, 12],
#                   [13, 14, 15],
#                   [16, 17, 18]]
# Your code here


In [ ]:
# Reshape 2x3 maxtrix b to an 1x6 row vector
# Expected result: [[1 2 3 4 5 6]]
b = np.array([[1,2,3],
              [4,5,6]])

# Your code here


In [ ]:
# Reshape the previous 1x6 row vector to an 6x1 column vector
# Expected result: [[1]
#                   [2]
#                   [3]
#                   [4]
#                   [5]
#                   [6]]

# Your code here


## Aggregate functions

In [ ]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s)

# Maximum number for the whole matrix
arr_max = ____ # fill in the blank
print("Max:", arr_max, sep = "\n")

# Minimum number for the whole matrix
arr_min = ____
print("Min:", arr_min, sep = "\n")

# Max element in each column
col_max = ____
print("Max in each column:", col_max, sep = "\n")

# Min element in each row
row_min = ____
print("Min in each row:", row_min, sep = "\n")

# Mean
arr_mean = ____
print("Mean:", arr_mean, sep = "\n")

# Standard Deviation
arr_sd = ____
print("Standard Dev.:", arr_sd, sep = "\n")

#Variance
arr_v = ____
print("Variance:", arr_v, sep = "\n")

## A bit more challenge

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
# Expected result: [ 0  1  2 -3 -4 -5 -6 -7 -8  9]
a = np.arange(10)

# Your code here


In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
# Expected result: [[0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]
#                   [0. 1. 2. 3. 4.]]

# Your code here


In [ ]:
# Give a random vector of size 10, replace the maximum value by 0
Z = np.random.random(10)

# Your code here


In [ ]:
# Find the common values between these 2 arrays:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
# Hint: take a look at np.intersect1d
# Your code here


In [ ]:
a = np.array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])
# Sort this array
# Expected result: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Your code here



In [ ]:
# For the same array above, return the indices that would sort the array
# Expected result: [3, 1, 5, 8, 7, 2, 9, 4, 0, 6]
# Your code here



In [ ]:
a = np.array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8],
       [8, 3, 8]])
# Sort each column of this matrix, in descending order
# Expected result:
# [[9, 8, 9],
# [8, 8, 8],
# [6, 3, 8],
# [5, 3, 6],
# [0, 0, 4]]
#
# your code here



In [ ]:
# Create an 1D array / row vector containing these float numbers 
# Expected output: [0.5, 0.6, 0.7]
#
# Note: try to use np.arange to solve this. Also try using np.linspace
# (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)
#
# Your code here



In [ ]:
np.random.seed(42)
a = np.random.rand(5)
b = np.array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])
print(a)
print(b)

# Write 1 line of code to check whether all elements in these 2 arrays are equal

In [ ]:
a = np.random.randint(10,size=5)
# Find the total memory size of this array in byte
# Hint: use a.itemsize to get the size (in byte) of 1 SINGLE ELEMENT
# Your code here


In [ ]:
# Convert array a above to type int8 and recalculate its memory size
# Hint: use astype to convert to another type
# Your code here


In [ ]:
a = np.array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8],
       [8, 3, 8]])
# Subtract each row of this matrix by the mean of each row
# Expected result: 
# [[ 2.        ,  1.        , -3.        ],
# [-0.66666667, -2.66666667,  3.33333333],
# [-0.66666667,  1.33333333, -0.66666667],
# [-2.66666667, -2.66666667,  5.33333333],
# [ 1.66666667, -3.33333333,  1.66666667]]

# Your code here




In [ ]:
a = np.arange(25).reshape(5,5)
# Swap the first row and the last row of this array
# Your code here

